version: '3.9'

services:
  app:
    build: ./app
    image: english-editor-bot-app:latest
    volumes:
      - ./app:/app
    ports:
      - "${APP_PORT:-8080}:80"
    environment:
      - HTTPS_PROXY=${HTTPS_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - APP_PORT=${APP_PORT:-8080}
      - BOT_TOKEN=${BOT_TOKEN}
      - API_KEY=${API_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    networks:
      - english-editor-bot

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - english-editor-bot

volumes:
  pg_data:

networks:
  english-editor-bot: